# Generated by Django 5.2.16 on 2026-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_material_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
