# Generated by Django 4.2.7 on 2026-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicsession_programme_courseoffering_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='level',
            name='unique_level_per_department',
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(condition=models.Q(('programme__isnull', True)), fields=('department', 'name'), name='unique_general_level_per_department'),
        ),
        migrations.AddConstraint(
            model_name='level',
            constraint=models.UniqueConstraint(fields=('programme', 'name'), name='unique_level_per_programme'),
        ),
    ]
