import * as React from 'react'
import type { ReactNode } from 'react'
import { zodResolver } from '@hookform/resolvers/zod'
import { ArrowLeft, ArrowRight } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { z } from 'zod'
import { api, getApiMessage } from '../api/client'
import { login } from '../features/authentication/services'
import { useAuthStore } from '../store/auth'

const schema = z.object({ email: z.string().email('Enter a valid email address.'), username: z.string().min(2, 'Use at least 2 characters.'), password: z.string().min(8, 'Use at least 8 characters.'), confirm_password: z.string() }).refine((data) => data.password === data.confirm_password, { path: ['confirm_password'], message: 'Passwords do not match.' })
type FormValues = z.infer<typeof schema>
export function Register() { const navigate = useNavigate(); const setSession = useAuthStore.setState; const [error, setError] = React.useState(''); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(schema) }); return <div className="flex min-h-screen items-center justify-center bg-ink px-6 py-12"><div className="w-full max-w-md rounded-3xl bg-paper p-7 shadow-soft sm:p-10"><Link to="/" className="mb-10 inline-flex items-center gap-2 text-sm font-bold text-ink/55"><ArrowLeft size={16} /> Back to library</Link><p className="mb-3 text-sm font-bold uppercase tracking-wider text-coral">Start here</p><h1 className="font-display text-5xl">Make room to learn.</h1><p className="mt-3 text-ink/60">Create your free student account.</p><form className="mt-8 space-y-4" onSubmit={handleSubmit(async (values) => { try { await api.post('/authentication/register/', values); const session = await login({ email: values.email, password: values.password }); setSession({ ...session }); window.location.reload() } catch (e) { setError(getApiMessage(e, 'Registration failed. Please check your details.')) } })}><Field label="Email" error={errors.email?.message}><input type="email" autoComplete="email" {...register('email')} /></Field><Field label="Username" error={errors.username?.message}><input autoComplete="username" {...register('username')} /></Field><Field label="Password" error={errors.password?.message}><input type="password" autoComplete="new-password" {...register('password')} /></Field><Field label="Confirm password" error={errors.confirm_password?.message}><input type="password" autoComplete="new-password" {...register('confirm_password')} /></Field>{error && <p role="alert" className="rounded-lg bg-coral/10 p-3 text-sm text-coral">{error}</p>}<button disabled={isSubmitting} className="flex w-full items-center justify-center gap-2 rounded-xl bg-coral px-5 py-3.5 font-bold text-white hover:bg-ink disabled:opacity-60">{isSubmitting ? 'Creating account...' : 'Create account'} <ArrowRight size={18} /></button></form><p className="mt-7 text-center text-sm text-ink/60">Already registered? <Link className="font-bold text-coral" to="/login">Sign in</Link></p></div></div> }
function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="block text-sm font-semibold">{label}<span className="mt-2 block [&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:border-ink/15 [&>input]:bg-cream [&>input]:px-4 [&>input]:py-3 [&>input]:outline-none [&>input]:focus:border-coral">{children}</span>{error && <span className="mt-1 block text-xs font-normal text-coral">{error}</span>}</label> }
